import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const {PDFDocument,degrees}=window.PDFLib;const el=id=>document.getElementById(id);
const fileInput=el('fileInput'),multiInput=el('multiInput'),thumbs=el('thumbs'),canvas=el('pdfCanvas');
let sourceDocs=[],pages=[],selected=0,renderToken=0;const uid=()=>Math.random().toString(36).slice(2);const setStatus=m=>el('status').textContent=m;
function controls(){const h=pages.length>0;['exportBtn','rotateLeft','rotateRight','deletePage','moveUp','moveDown'].forEach(id=>el(id).disabled=!h);el('moveUp').disabled=!h||selected===0;el('moveDown').disabled=!h||selected===pages.length-1;el('pageCount').textContent=pages.length;el('emptyState').classList.toggle('hidden',h);el('viewerWrap').classList.toggle('hidden',!h)}
async function load(bytes){const pdfjsBytes=new Uint8Array(bytes).slice();const pdfLibBytes=new Uint8Array(bytes).slice();const pdfjsDoc=await pdfjsLib.getDocument({data:pdfjsBytes}).promise;const libDoc=await PDFDocument.load(pdfLibBytes);const docIndex=sourceDocs.length;sourceDocs.push({pdfjsDoc,libDoc});for(let i=0;i<pdfjsDoc.numPages;i++)pages.push({docIndex,pageIndex:i,rotation:0,id:uid()})}
async function openFiles(files,replace=false){const list=[...files].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'));if(!list.length)return;try{setStatus('Loading PDF…');if(replace){sourceDocs=[];pages=[];selected=0}for(const f of list)await load(await f.arrayBuffer());if(selected>=pages.length)selected=Math.max(0,pages.length-1);await rebuild();setStatus(pages.length+' page(s) ready')}catch(e){console.error('PDF open error:',e);setStatus('Could not open PDF');alert('This PDF could not be opened. Please try another PDF.')}} 
async function renderPage(){if(!pages.length)return;const token=++renderToken,item=pages[selected],page=await sourceDocs[item.docIndex].pdfjsDoc.getPage(item.pageIndex+1),base=page.getViewport({scale:1.4,rotation:item.rotation}),maxWidth=Math.min(920,Math.max(320,el('dropZone').clientWidth-80)),scale=Math.min(1.6,maxWidth/base.width*1.4),vp=page.getViewport({scale,rotation:item.rotation}),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(vp.width*dpr);canvas.height=Math.floor(vp.height*dpr);canvas.style.width=vp.width+'px';canvas.style.height=vp.height+'px';const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);if(token!==renderToken)return;await page.render({canvasContext:c,viewport:vp}).promise;el('pageLabel').textContent='Page '+(selected+1)+' of '+pages.length}
async function thumb(item,index){const box=document.createElement('div');box.className='thumb'+(index===selected?' active':'');box.draggable=true;const c=document.createElement('canvas'),p=await sourceDocs[item.docIndex].pdfjsDoc.getPage(item.pageIndex+1),vp=p.getViewport({scale:.28,rotation:item.rotation});c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const meta=document.createElement('div');meta.className='thumb-meta';meta.innerHTML='<span>'+(index+1)+'</span><span>'+(item.rotation?item.rotation+'°':'')+'</span>';box.append(c,meta);box.onclick=()=>{selected=index;rebuild(false)};box.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',String(index)));box.addEventListener('dragover',e=>e.preventDefault());box.addEventListener('drop',e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain')),to=index;if(from===to)return;const[m]=pages.splice(from,1);pages.splice(to,0,m);selected=to;rebuild()});thumbs.appendChild(box)}
async function rebuild(rt=true){controls();if(rt){thumbs.innerHTML='';for(let i=0;i<pages.length;i++)await thumb(pages[i],i)}else[...thumbs.children].forEach((n,i)=>n.classList.toggle('active',i===selected));await renderPage()}
async function exportPdf(){if(!pages.length)return;setStatus('Building PDF…');try{const out=await PDFDocument.create();for(const item of pages){const src=sourceDocs[item.docIndex].libDoc,[copied]=await out.copyPages(src,[item.pageIndex]);if(item.rotation){const current=copied.getRotation().angle||0;copied.setRotation(degrees((current+item.rotation)%360))}out.addPage(copied)}const bytes=await out.save(),blob=new Blob([bytes],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pdfcraft-edited.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus('Downloaded edited PDF')}catch(e){console.error(e);setStatus('Export failed')}}
function rotate(d){if(!pages.length)return;pages[selected].rotation=(pages[selected].rotation+d+360)%360;rebuild()}function del(){if(!pages.length)return;pages.splice(selected,1);if(selected>=pages.length)selected=Math.max(0,pages.length-1);rebuild()}function move(d){const to=selected+d;if(to<0||to>=pages.length)return;[pages[selected],pages[to]]=[pages[to],pages[selected]];selected=to;rebuild()}
el('openBtn').onclick=()=>fileInput.click();el('chooseBtn').onclick=()=>fileInput.click();el('mergeBtn').onclick=()=>multiInput.click();el('chooseMultiBtn').onclick=()=>multiInput.click();el('addBtn').onclick=()=>multiInput.click();fileInput.onchange=e=>openFiles(e.target.files,true);multiInput.onchange=e=>openFiles(e.target.files,false);el('exportBtn').onclick=exportPdf;el('rotateLeft').onclick=()=>rotate(-90);el('rotateRight').onclick=()=>rotate(90);el('deletePage').onclick=del;el('moveUp').onclick=()=>move(-1);el('moveDown').onclick=()=>move(1);const drop=el('dropZone');['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>openFiles(e.dataTransfer.files,pages.length===0));window.addEventListener('resize',()=>{if(pages.length)renderPage()});controls();